// ============================================================
// IT学習ポータル - コンテンツデータ
// ============================================================

const CATEGORIES = {
  basics:      { label: 'IT基礎',        icon: 'fa-microchip',     color: '#6366f1' },
  programming: { label: 'プログラミング', icon: 'fa-code',          color: '#0ea5e9' },
  network:     { label: 'ネットワーク',   icon: 'fa-network-wired', color: '#14b8a6' },
  database:    { label: 'データベース',   icon: 'fa-database',      color: '#f59e0b' },
  ai_ml:       { label: 'AI・機械学習',   icon: 'fa-brain',         color: '#8b5cf6' },
  ai_security: { label: 'AIセキュリティ', icon: 'fa-shield-halved', color: '#ef4444' },
  security:    { label: 'セキュリティ',   icon: 'fa-lock',          color: '#f97316' },
  cloud:       { label: 'クラウド',       icon: 'fa-cloud',         color: '#3b82f6' },
  business:    { label: 'ビジネス技術',   icon: 'fa-briefcase',     color: '#10b981' },
  paper:       { label: '論文・研究',     icon: 'fa-file-lines',    color: '#6b7280' },
};

const LEVELS = {
  beginner:     { label: '初学者', color: '#10b981' },
  intermediate: { label: '中級者', color: '#f59e0b' },
  advanced:     { label: '上級者', color: '#ef4444' },
};

const TYPES = {
  youtube: { label: 'YouTube',   icon: 'fa-brands fa-youtube', color: '#ff0000' },
  paper:   { label: '論文',       icon: 'fa-file-lines',        color: '#6b7280' },
  article: { label: '記事・書籍', icon: 'fa-book-open',         color: '#0ea5e9' },
  course:  { label: 'コース',     icon: 'fa-graduation-cap',    color: '#8b5cf6' },
};

const COURSES = [
  // =================== IT基礎 ===================
  {
    id: 'basics-001',
    title: 'コンピュータサイエンス入門 ― CPU・メモリ・OSの仕組み',
    description: 'コンピュータの基本構成要素（CPU・RAM・ストレージ）から2進数・16進数の計算、OSの役割まで、情報系学習の絶対的土台を丁寧に解説。',
    category: 'basics', level: 'beginner', type: 'youtube',
    tags: ['CPU', 'メモリ', 'OS', '2進数', 'コンピュータ基礎'],
    url: 'https://www.youtube.com/watch?v=zOjov-2OZ0E',
    youtubeId: 'zOjov-2OZ0E',
    channel: 'CS50 Harvard', duration: '約45分', year: 2024,
  },
  {
    id: 'basics-002',
    title: '情報理論の基礎 ― エントロピーと符号化',
    description: 'シャノンの情報理論から始まり、エントロピー・ハフマン符号・データ圧縮の原理まで解説。情報量の「測り方」が直感的に理解できます。',
    category: 'basics', level: 'beginner', type: 'youtube',
    tags: ['情報理論', 'エントロピー', 'シャノン', '符号化'],
    url: 'https://www.youtube.com/watch?v=AuX7nPBqDts',
    youtubeId: 'AuX7nPBqDts',
    channel: '3Blue1Brown', duration: '約60分', year: 2023,
  },
  {
    id: 'basics-003',
    title: 'アルゴリズムとデータ構造 入門編',
    description: '配列・リスト・スタック・キュー・木構造・グラフ、ソートアルゴリズムをアニメーション付きで学ぶ。計算量O記法も完全解説。',
    category: 'basics', level: 'beginner', type: 'youtube',
    tags: ['アルゴリズム', 'データ構造', 'O記法', 'ソート'],
    url: 'https://www.youtube.com/watch?v=8hly31xKli0',
    youtubeId: '8hly31xKli0',
    channel: 'freeCodeCamp.org', duration: '約90分', year: 2024,
  },
  {
    id: 'basics-004',
    title: '論理回路と論理演算の基礎',
    description: 'AND/OR/NOT/XORゲートから始まり、加算器・フリップフロップ・レジスタまで、ハードウェアの論理設計を図解付きで学びます。',
    category: 'basics', level: 'beginner', type: 'youtube',
    tags: ['論理回路', '論理演算', 'AND', 'OR', '加算器'],
    url: 'https://www.youtube.com/watch?v=gI-qXk7XojA',
    youtubeId: 'gI-qXk7XojA',
    channel: 'Crash Course', duration: '約50分', year: 2023,
  },
  {
    id: 'basics-005',
    title: 'オペレーティングシステム詳解',
    description: 'プロセス管理・スレッド・メモリ管理・ファイルシステム・デッドロックなど、OSが何をしているかを体系的に理解する中級者向け講座。',
    category: 'basics', level: 'intermediate', type: 'youtube',
    tags: ['OS', 'プロセス', 'スレッド', 'メモリ管理'],
    url: 'https://www.youtube.com/watch?v=vBURTt97EkA',
    youtubeId: 'vBURTt97EkA',
    channel: 'freeCodeCamp.org', duration: '約120分', year: 2024,
  },

  // =================== プログラミング ===================
  {
    id: 'prog-001',
    title: 'Python 完全入門 ― 変数・制御・関数から始める',
    description: '変数の型・if文・for文・関数・リスト・辞書・ファイルI/Oまで、Pythonの基礎を実際にコードを動かしながら習得。',
    category: 'programming', level: 'beginner', type: 'youtube',
    tags: ['Python', '変数', '制御文', '関数', 'リスト'],
    url: 'https://www.youtube.com/watch?v=rfscVS0vtbw',
    youtubeId: 'rfscVS0vtbw',
    channel: 'freeCodeCamp.org', duration: '約4時間', year: 2025,
  },
  {
    id: 'prog-002',
    title: 'JavaScript 完全入門 ― 基礎から非同期まで',
    description: 'DOM操作・非同期処理（async/await）・ES6+構文・TypeScript型定義まで。ブラウザとNode.js両方で動くJSの核心を体系的に学びます。',
    category: 'programming', level: 'beginner', type: 'youtube',
    tags: ['JavaScript', 'TypeScript', 'DOM', '非同期', 'ES6'],
    url: 'https://www.youtube.com/watch?v=PkZNo7MFNFg',
    youtubeId: 'PkZNo7MFNFg',
    channel: 'freeCodeCamp.org', duration: '約3時間', year: 2025,
  },
  {
    id: 'prog-003',
    title: 'HTML & CSS でWebページを作ろう',
    description: 'Flexbox・Grid・レスポンシブデザイン・CSS変数・アニメーションまで。デザインセンス不要で美しいページを作る実践的な入門講座。',
    category: 'programming', level: 'beginner', type: 'youtube',
    tags: ['HTML', 'CSS', 'Flexbox', 'Grid', 'レスポンシブ'],
    url: 'https://www.youtube.com/watch?v=mU6anWqZJcc',
    youtubeId: 'mU6anWqZJcc',
    channel: 'freeCodeCamp.org', duration: '約2時間', year: 2024,
  },
  {
    id: 'prog-008',
    title: 'Git & GitHub 完全マスター',
    description: 'ブランチ戦略・マージ・リベース・コンフリクト解決・Pull Request・GitHub Actionsまで、チーム開発に必須のGit操作を基礎から学ぶ。',
    category: 'programming', level: 'beginner', type: 'youtube',
    tags: ['Git', 'GitHub', 'ブランチ', 'マージ', 'CI/CD'],
    url: 'https://www.youtube.com/watch?v=RGOj5yH7evk',
    youtubeId: 'RGOj5yH7evk',
    channel: 'freeCodeCamp.org', duration: '約2時間', year: 2025,
  },
  {
    id: 'prog-004',
    title: 'Pythonデータ分析 ― pandas・NumPy・Matplotlib実践',
    description: 'DataFrameの操作・集計・結合・可視化まで、データサイエンスの必須ライブラリをビジネスデータを使って実践的に習得します。',
    category: 'programming', level: 'intermediate', type: 'youtube',
    tags: ['Python', 'pandas', 'NumPy', 'Matplotlib', 'データ分析'],
    url: 'https://www.youtube.com/watch?v=GPVsHOlRBBI',
    youtubeId: 'GPVsHOlRBBI',
    channel: 'Keith Galli', duration: '約3時間', year: 2025,
  },
  {
    id: 'prog-005',
    title: 'React 19 + Next.js 15 実践アプリ開発',
    description: 'コンポーネント設計・hooks・状態管理・Server Components・App Routerを使ったフルスタックWebアプリ開発の最新手法を学ぶ。',
    category: 'programming', level: 'intermediate', type: 'youtube',
    tags: ['React', 'Next.js', 'TypeScript', 'Server Components'],
    url: 'https://www.youtube.com/watch?v=bMknfKXIFA8',
    youtubeId: 'bMknfKXIFA8',
    channel: 'freeCodeCamp.org', duration: '約5時間', year: 2025,
  },
  {
    id: 'prog-006',
    title: 'システム設計入門 ― 大規模サービスの設計思想',
    description: 'スケーラビリティ・可用性・一貫性のトレードオフ、キャッシュ設計・メッセージキュー・マイクロサービス分割など、実務設計力を鍛える。',
    category: 'programming', level: 'advanced', type: 'youtube',
    tags: ['システム設計', 'スケーラビリティ', 'マイクロサービス', 'キャッシュ'],
    url: 'https://www.youtube.com/watch?v=i53Gi_K3o7I',
    youtubeId: 'i53Gi_K3o7I',
    channel: 'Gaurav Sen', duration: '約4時間', year: 2024,
  },
  {
    id: 'prog-007',
    title: 'クリーンアーキテクチャ実践ガイド',
    description: '依存性逆転の原則・ユースケース層・エンティティ層を実際のコードで実装。SOLID原則とレイヤー設計の実践方法を体系的に学ぶ。',
    category: 'programming', level: 'advanced', type: 'article',
    tags: ['クリーンアーキテクチャ', 'SOLID', '依存性逆転', 'レイヤー設計'],
    url: 'https://www.google.com/search?q=クリーンアーキテクチャ+実践',
    author: 'Robert C. Martin ほか各種解説', duration: '約2時間', year: 2024,
  },

  // =================== ネットワーク ===================
  {
    id: 'net-001',
    title: 'TCP/IP 完全入門 ― ネットワークの仕組みを理解する',
    description: 'OSI参照モデル・IP・TCP・UDP・DNS・HTTPの仕組みをパケットレベルで解説。ネットワーク資格対策にも最適。',
    category: 'network', level: 'beginner', type: 'youtube',
    tags: ['TCP/IP', 'OSI', 'DNS', 'HTTP', 'ネットワーク基礎'],
    url: 'https://www.youtube.com/watch?v=qiQR5rTSshw',
    youtubeId: 'qiQR5rTSshw',
    channel: 'Computerphile', duration: '約90分', year: 2024,
  },
  {
    id: 'net-002',
    title: 'HTTP/HTTPS と TLS の仕組み',
    description: 'HTTPリクエスト/レスポンスの構造・HTTPSでの暗号化・TLSハンドシェイク・証明書の仕組みまで。Webセキュリティの根幹を理解する。',
    category: 'network', level: 'beginner', type: 'youtube',
    tags: ['HTTP', 'HTTPS', 'TLS', 'SSL', '証明書', '暗号化'],
    url: 'https://www.youtube.com/watch?v=j9QmMEWmcfo',
    youtubeId: 'j9QmMEWmcfo',
    channel: 'Fireship', duration: '約60分', year: 2024,
  },
  {
    id: 'net-003',
    title: 'ルーティングプロトコル詳解 ― OSPF・BGP',
    description: '静的ルーティングから動的ルーティング（RIP・OSPF・BGP）まで。インターネットの経路制御がどう機能するかを実機演習を交えて解説。',
    category: 'network', level: 'intermediate', type: 'youtube',
    tags: ['ルーティング', 'OSPF', 'BGP', 'RIP', '経路制御'],
    url: 'https://www.youtube.com/watch?v=A1KX6Z5v6vg',
    youtubeId: 'A1KX6Z5v6vg',
    channel: 'Network Direction', duration: '約120分', year: 2023,
  },
  {
    id: 'net-004',
    title: 'ゼロトラストネットワーク ― 境界防御からの脱却',
    description: 'ゼロトラストの概念・NIST SP 800-207・マイクロセグメンテーション・IDプロバイダ連携など、現代のネットワークセキュリティアーキテクチャ。',
    category: 'network', level: 'advanced', type: 'article',
    tags: ['ゼロトラスト', 'NIST', 'マイクロセグメント', 'IAM'],
    url: 'https://www.google.com/search?q=ゼロトラストネットワーク+NIST+解説',
    author: 'NIST SP 800-207 / 各種解説', duration: '約60分', year: 2024,
  },

  // =================== データベース ===================
  {
    id: 'db-001',
    title: 'SQL 完全入門 ― SELECT から JOIN まで',
    description: 'SELECT・WHERE・GROUP BY・JOIN・サブクエリ・インデックスの使い方まで、SQLの基礎を実際のデータを操作しながら習得。',
    category: 'database', level: 'beginner', type: 'youtube',
    tags: ['SQL', 'SELECT', 'JOIN', 'MySQL', 'PostgreSQL'],
    url: 'https://www.youtube.com/watch?v=HXV3zeQKqGY',
    youtubeId: 'HXV3zeQKqGY',
    channel: 'freeCodeCamp.org', duration: '約3時間', year: 2025,
  },
  {
    id: 'db-002',
    title: 'データベース設計の基礎 ― ER図・正規化',
    description: 'ER図の書き方・第1〜第3正規形・テーブル設計のアンチパターンを実例で解説。「なぜそう設計するか」の思考プロセスが身につく。',
    category: 'database', level: 'beginner', type: 'youtube',
    tags: ['データベース設計', 'ER図', '正規化', 'テーブル設計'],
    url: 'https://www.youtube.com/watch?v=ztHopE5Wnpc',
    youtubeId: 'ztHopE5Wnpc',
    channel: 'Lucidchart', duration: '約90分', year: 2024,
  },
  {
    id: 'db-003',
    title: 'SQLクエリ最適化とインデックス戦略',
    description: 'EXPLAIN解析・インデックス設計・クエリプランの読み方・パーティショニング・統計情報更新など、本番DBのパフォーマンスチューニング手法。',
    category: 'database', level: 'intermediate', type: 'youtube',
    tags: ['SQL最適化', 'インデックス', 'EXPLAIN', 'パフォーマンス'],
    url: 'https://www.youtube.com/watch?v=BHwzDmr6d7s',
    youtubeId: 'BHwzDmr6d7s',
    channel: 'Hussein Nasser', duration: '約2時間', year: 2024,
  },
  {
    id: 'db-004',
    title: 'NoSQLデータベース入門 ― MongoDB・Redis・Cassandra',
    description: 'ドキュメントDB・KVS・カラム指向DBの使い分け、CAP定理、結果整合性とは何かを実例を通じて学ぶ。',
    category: 'database', level: 'intermediate', type: 'youtube',
    tags: ['NoSQL', 'MongoDB', 'Redis', 'CAP定理'],
    url: 'https://www.youtube.com/watch?v=0buKQHokLK8',
    youtubeId: '0buKQHokLK8',
    channel: 'Fireship', duration: '約2時間', year: 2024,
  },

  // =================== AI・機械学習 ===================
  {
    id: 'ai-001',
    title: '機械学習 入門 ― 線形回帰から始める AI',
    description: '機械学習とは何か・教師あり/なし学習・線形回帰・ロジスティック回帰・決定木をPythonで実装しながら学ぶ。数学的な直感も丁寧に解説。',
    category: 'ai_ml', level: 'beginner', type: 'youtube',
    tags: ['機械学習', '線形回帰', 'ロジスティック回帰', '決定木'],
    url: 'https://www.youtube.com/watch?v=NWONeJKn6kc',
    youtubeId: 'NWONeJKn6kc',
    channel: 'StatQuest', duration: '約3時間', year: 2025,
  },
  {
    id: 'ai-002',
    title: 'ニューラルネットワーク & 深層学習 基礎',
    description: 'パーセプトロンから始まり、多層ニューラルネットワーク・バックプロパゲーション・活性化関数・バッチ正規化まで。PyTorchで実装しながら理解を深める。',
    category: 'ai_ml', level: 'beginner', type: 'youtube',
    tags: ['ニューラルネット', '深層学習', 'PyTorch', 'バックプロパゲーション'],
    url: 'https://www.youtube.com/watch?v=aircAruvnKk',
    youtubeId: 'aircAruvnKk',
    channel: '3Blue1Brown', duration: '約4時間', year: 2024,
  },
  {
    id: 'ai-003',
    title: 'Transformer & 自己注意機構の完全解説',
    description: '「Attention Is All You Need」論文の内容をゼロから解説。マルチヘッドアテンション・位置エンコーディング・エンコーダ/デコーダ構造をコード付きで理解する。',
    category: 'ai_ml', level: 'advanced', type: 'paper',
    tags: ['Transformer', 'Attention', 'NLP', 'BERT', 'GPT'],
    url: 'https://arxiv.org/abs/1706.03762',
    author: 'Vaswani et al. (2017)', duration: '約3時間', year: 2017,
  },
  {
    id: 'ai-004',
    title: 'ChatGPT・Claude API 実践活用術',
    description: 'OpenAI API / Anthropic APIを使った実用アプリ開発。プロンプトエンジニアリング・Few-shot・Function Calling・ストリーミング出力まで実践的に学ぶ。',
    category: 'ai_ml', level: 'intermediate', type: 'youtube',
    tags: ['ChatGPT', 'Claude', 'API', 'プロンプトエンジニアリング', 'LLM'],
    url: 'https://www.youtube.com/watch?v=uRQH2CFvedY',
    youtubeId: 'uRQH2CFvedY',
    channel: 'Andrej Karpathy', duration: '約3時間', year: 2025,
  },
  {
    id: 'ai-005',
    title: 'RAG（検索拡張生成）実装ガイド',
    description: 'ベクトルDB・埋め込みモデル・ドキュメント分割・リランキングを組み合わせてRAGパイプラインをゼロから構築。LangChain・LlamaIndex両方を解説。',
    category: 'ai_ml', level: 'advanced', type: 'article',
    tags: ['RAG', 'ベクトルDB', 'LangChain', 'LlamaIndex', '埋め込み'],
    url: 'https://www.google.com/search?q=RAG+実装+LangChain',
    author: '各種技術ブログ', duration: '約3時間', year: 2025,
  },
  {
    id: 'ai-006',
    title: 'LLMファインチューニング & LoRA実践',
    description: 'LoRA・QLoRA・DPO・SFTなど最新のファインチューニング手法をHugging Face Transformersで実装。小さなモデルを特定タスク向けに高精度化する技術。',
    category: 'ai_ml', level: 'advanced', type: 'youtube',
    tags: ['LoRA', 'ファインチューニング', 'HuggingFace', 'LLM', 'QLoRA'],
    url: 'https://www.youtube.com/watch?v=eC6Hd1hFvos',
    youtubeId: 'eC6Hd1hFvos',
    channel: 'Andrej Karpathy', duration: '約4時間', year: 2025,
  },
  {
    id: 'ai-007',
    title: '生成AI ビジネス活用 ― 実務で使える50のユースケース',
    description: '文書作成・コード生成・データ分析・顧客対応自動化など、職場で今すぐ使える生成AI活用術を具体例とプロンプト例付きで紹介。',
    category: 'ai_ml', level: 'intermediate', type: 'youtube',
    tags: ['生成AI', 'ChatGPT', 'ビジネス活用', 'DX', 'プロンプト'],
    url: 'https://www.youtube.com/watch?v=oc_apQqHGFQ',
    youtubeId: 'oc_apQqHGFQ',
    channel: 'AI Explained', duration: '約2時間', year: 2025,
  },
  {
    id: 'ai-008',
    title: 'マルチモーダルAI ― 画像・音声・テキスト統合',
    description: 'GPT-4o・Gemini・Claude 3などのマルチモーダルモデルの仕組みと活用方法。Vision Transformer（ViT）の技術解説も含む。',
    category: 'ai_ml', level: 'intermediate', type: 'youtube',
    tags: ['マルチモーダル', 'GPT-4o', 'Gemini', 'ViT', '画像認識'],
    url: 'https://www.youtube.com/watch?v=vjyfIcc_BKA',
    youtubeId: 'vjyfIcc_BKA',
    channel: 'Yannic Kilcher', duration: '約2時間', year: 2025,
  },

  // =================== AIセキュリティ ===================
  {
    id: 'aisec-001',
    title: 'AI倫理とリスク管理 ― 安全なAI活用の考え方',
    description: 'AIバイアス・フェアネス・説明可能性・プライバシーリスクを具体例で解説。企業がAIを導入する際に必ず検討すべきガバナンス観点を学ぶ。',
    category: 'ai_security', level: 'beginner', type: 'youtube',
    tags: ['AI倫理', 'バイアス', '説明可能AI', 'プライバシー'],
    url: 'https://www.youtube.com/watch?v=7Xuv0_hqRvA',
    youtubeId: '7Xuv0_hqRvA',
    channel: 'MIT OpenCourseWare', duration: '約60分', year: 2024,
  },
  {
    id: 'aisec-002',
    title: 'プロンプトインジェクション攻撃と防御',
    description: 'Direct/Indirect プロンプトインジェクション・ジェイルブレイク手法の仕組みと、システムプロンプト設計・入力検証・出力フィルタリングによる防御策を解説。',
    category: 'ai_security', level: 'intermediate', type: 'article',
    tags: ['プロンプトインジェクション', 'ジェイルブレイク', 'LLMセキュリティ', 'OWASP LLM'],
    url: 'https://owasp.org/www-project-top-10-for-large-language-model-applications/',
    author: 'OWASP LLM Top 10', duration: '約90分', year: 2025,
  },
  {
    id: 'aisec-003',
    title: '敵対的攻撃（Adversarial Attacks）入門',
    description: 'FGSM・PGD・CarliniWagner攻撃など、AIモデルを騙す敵対的サンプルの仕組みと、敵対的訓練・入力前処理による防御手法を実装付きで解説。',
    category: 'ai_security', level: 'intermediate', type: 'youtube',
    tags: ['敵対的攻撃', 'FGSM', '敵対的訓練', 'AML'],
    url: 'https://www.youtube.com/watch?v=CIfsB_EYsVI',
    youtubeId: 'CIfsB_EYsVI',
    channel: 'Lex Fridman', duration: '約2時間', year: 2024,
  },
  {
    id: 'aisec-004',
    title: 'AIモデルの脆弱性 ― モデル盗取・データポイズニング',
    description: 'MLシステムへの主要脅威（モデル抽出・訓練データ漏洩・バックドア攻撃）をサーベイ論文ベースで包括的に解説。',
    category: 'ai_security', level: 'advanced', type: 'paper',
    tags: ['モデル盗取', 'データポイズニング', 'バックドア', 'MLセキュリティ'],
    url: 'https://arxiv.org/search/?query=machine+learning+security+attacks',
    author: '各種セキュリティ論文', duration: '約4時間', year: 2024,
  },
  {
    id: 'aisec-005',
    title: '生成AIのセキュリティリスク ― OWASP LLM Top 10',
    description: 'OWASP LLM Top 10（2025）を全項目解説。LLM01〜LLM10まで、各リスクの攻撃シナリオと緩和策を詳述。',
    category: 'ai_security', level: 'intermediate', type: 'article',
    tags: ['OWASP', 'LLM', 'Top10', '生成AI'],
    url: 'https://owasp.org/www-project-top-10-for-large-language-model-applications/',
    author: 'OWASP Foundation', duration: '約2時間', year: 2025,
  },
  {
    id: 'aisec-006',
    title: 'AIガバナンス ― EU AI Act と国際規制動向',
    description: 'EU AI法のリスク分類・日本のAI戦略・ISO/IEC 42001 AI管理システムなど、AIに関わるエンジニアが知るべき規制と標準。',
    category: 'ai_security', level: 'advanced', type: 'article',
    tags: ['EU AI Act', 'AIガバナンス', 'ISO 42001', 'AI規制'],
    url: 'https://www.google.com/search?q=EU+AI+Act+日本語+解説',
    author: '各種政策解説', duration: '約2時間', year: 2025,
  },

  // =================== セキュリティ ===================
  {
    id: 'sec-001',
    title: '情報セキュリティ 基礎 ― CIA・暗号・認証を学ぶ',
    description: '機密性・完全性・可用性（CIA）・共通鍵/公開鍵暗号・デジタル署名・認証の仕組みを、実例と図解で丁寧に解説。',
    category: 'security', level: 'beginner', type: 'youtube',
    tags: ['情報セキュリティ', 'CIA', '暗号化', '認証'],
    url: 'https://www.youtube.com/watch?v=inWWhr5tnEA',
    youtubeId: 'inWWhr5tnEA',
    channel: 'IBM Technology', duration: '約90分', year: 2024,
  },
  {
    id: 'sec-002',
    title: 'OWASP Top 10 2025 ― Web脆弱性の完全解説',
    description: 'A01:アクセス制御〜A10:SSRF まで、WebアプリケーションのTop10脆弱性を攻撃コードと防御コードのセットで解説。',
    category: 'security', level: 'intermediate', type: 'article',
    tags: ['OWASP', 'SQLインジェクション', 'XSS', 'CSRF'],
    url: 'https://owasp.org/www-project-top-ten/',
    author: 'OWASP Foundation', duration: '約3時間', year: 2025,
  },
  {
    id: 'sec-003',
    title: '暗号技術の基礎 ― AES・RSA・楕円曲線暗号',
    description: '対称鍵暗号（AES）・非対称鍵暗号（RSA・ECC）・ハッシュ関数（SHA-256）の数学的背景をわかりやすく解説。',
    category: 'security', level: 'beginner', type: 'youtube',
    tags: ['AES', 'RSA', '楕円曲線', 'SHA-256', '暗号理論'],
    url: 'https://www.youtube.com/watch?v=AQDCe585Lnc',
    youtubeId: 'AQDCe585Lnc',
    channel: 'Computerphile', duration: '約2時間', year: 2024,
  },
  {
    id: 'sec-004',
    title: 'ペネトレーションテスト 実践入門',
    description: 'Kali Linux・Nmap・Metasploit・Burp Suite を使った倫理的ハッキングの基礎。脆弱性スキャン・エクスプロイト・レポート作成の流れを学ぶ（学習環境向け）。',
    category: 'security', level: 'intermediate', type: 'youtube',
    tags: ['ペネトレーションテスト', 'Kali Linux', 'Metasploit', 'Burp Suite'],
    url: 'https://www.youtube.com/watch?v=3Kq1MIfTWCE',
    youtubeId: '3Kq1MIfTWCE',
    channel: 'freeCodeCamp.org', duration: '約4時間', year: 2024,
  },
  {
    id: 'sec-005',
    title: 'インシデント対応手順 ― 発生から復旧まで',
    description: 'インシデント検知・初動対応・証拠保全・封じ込め・根本原因分析・再発防止まで、企業でのセキュリティインシデント対応の全フローを解説。',
    category: 'security', level: 'intermediate', type: 'article',
    tags: ['インシデント対応', 'CSIRT', 'フォレンジック', 'SOC'],
    url: 'https://www.google.com/search?q=インシデント対応+手順+CSIRT',
    author: 'IPA・各種セキュリティガイド', duration: '約2時間', year: 2024,
  },
  {
    id: 'sec-006',
    title: 'バグバウンティ & CTF入門',
    description: 'HackTheBox・TryHackMe・picoCTFなどを使ったCTFへの参加方法と、バグバウンティプログラムへの参加ガイド。',
    category: 'security', level: 'advanced', type: 'youtube',
    tags: ['CTF', 'バグバウンティ', 'HackTheBox', 'TryHackMe'],
    url: 'https://www.youtube.com/watch?v=lxJpKUoX-6E',
    youtubeId: 'lxJpKUoX-6E',
    channel: 'LiveOverflow', duration: '約3時間', year: 2025,
  },

  // =================== クラウド ===================
  {
    id: 'cloud-001',
    title: 'AWS 入門 ― EC2・S3・RDS・Lambda から始める',
    description: 'AWSの主要サービス（EC2・S3・RDS・Lambda・VPC・IAM）を実際に操作しながら学ぶ入門コース。AWSクラウドプラクティショナー取得を視野に入れた構成。',
    category: 'cloud', level: 'beginner', type: 'youtube',
    tags: ['AWS', 'EC2', 'S3', 'Lambda', 'クラウド入門'],
    url: 'https://www.youtube.com/watch?v=3hLmDS9CT6M',
    youtubeId: '3hLmDS9CT6M',
    channel: 'freeCodeCamp.org', duration: '約5時間', year: 2025,
  },
  {
    id: 'cloud-002',
    title: 'Docker コンテナ入門 ― 仮想化の新常識',
    description: 'Dockerの仕組み・Dockerfile作成・イメージビルド・docker-compose・Dockerネットワークまで。コンテナ技術の完全入門。',
    category: 'cloud', level: 'intermediate', type: 'youtube',
    tags: ['Docker', 'コンテナ', 'Dockerfile', 'docker-compose'],
    url: 'https://www.youtube.com/watch?v=fqMOX6JJhGo',
    youtubeId: 'fqMOX6JJhGo',
    channel: 'freeCodeCamp.org', duration: '約3時間', year: 2025,
  },
  {
    id: 'cloud-003',
    title: 'Kubernetes 実践 ― コンテナオーケストレーション',
    description: 'Pod・Deployment・Service・Ingress・ConfigMap・HPA など、K8sのコアリソースを実際のクラスターで操作しながら学ぶ実践的な内容。',
    category: 'cloud', level: 'intermediate', type: 'youtube',
    tags: ['Kubernetes', 'K8s', 'Pod', 'Deployment'],
    url: 'https://www.youtube.com/watch?v=X48VuDVv0do',
    youtubeId: 'X48VuDVv0do',
    channel: 'TechWorld with Nana', duration: '約5時間', year: 2025,
  },
  {
    id: 'cloud-004',
    title: 'サーバーレスアーキテクチャ ― AWS Lambda & API Gateway',
    description: 'AWS Lambda関数の設計・API Gateway統合・DynamoDB連携・EventBridgeトリガー。サーバーレスの設計パターンとコスト最適化のポイントを解説。',
    category: 'cloud', level: 'intermediate', type: 'youtube',
    tags: ['サーバーレス', 'Lambda', 'API Gateway', 'DynamoDB'],
    url: 'https://www.youtube.com/watch?v=97q30JjEq9Y',
    youtubeId: '97q30JjEq9Y',
    channel: 'AWS Events', duration: '約3時間', year: 2024,
  },
  {
    id: 'cloud-005',
    title: 'Infrastructure as Code ― Terraform実践',
    description: 'HCL構文・リソース定義・モジュール・ステート管理・CI/CDとの統合まで。インフラをコードで管理するTerraformの実践的な使い方を学ぶ。',
    category: 'cloud', level: 'advanced', type: 'youtube',
    tags: ['Terraform', 'IaC', 'AWS', 'インフラ自動化'],
    url: 'https://www.youtube.com/watch?v=SLB_c_ayRMo',
    youtubeId: 'SLB_c_ayRMo',
    channel: 'freeCodeCamp.org', duration: '約4時間', year: 2025,
  },

  // =================== ビジネス技術 ===================
  {
    id: 'biz-001',
    title: 'アジャイル開発 & スクラム入門',
    description: 'スプリント・バックログ・スタンドアップ・レトロスペクティブなど、スクラムの実践的な進め方を解説。アジャイルマニフェストの思想も含めて体系的に学ぶ。',
    category: 'business', level: 'beginner', type: 'youtube',
    tags: ['アジャイル', 'スクラム', 'スプリント', 'バックログ'],
    url: 'https://www.youtube.com/watch?v=9TycLR0TqFA',
    youtubeId: '9TycLR0TqFA',
    channel: 'Atlassian', duration: '約90分', year: 2024,
  },
  {
    id: 'biz-002',
    title: 'DevOps実践ガイド ― CI/CDパイプライン構築',
    description: 'GitHub Actions・Jenkins・ArgoCD を使ったCI/CDパイプラインの構築方法。テスト自動化・コンテナビルド・本番デプロイまでの一連の流れを実演。',
    category: 'business', level: 'intermediate', type: 'youtube',
    tags: ['DevOps', 'CI/CD', 'GitHub Actions', 'Jenkins'],
    url: 'https://www.youtube.com/watch?v=scEDHsr3APg',
    youtubeId: 'scEDHsr3APg',
    channel: 'TechWorld with Nana', duration: '約4時間', year: 2025,
  },
  {
    id: 'biz-003',
    title: 'エンジニアのドキュメント作成術',
    description: 'API仕様書・設計書・障害報告書・READMEの書き方。「読み手に伝わる」技術文書を書くための構成・図解・命名規則のベストプラクティス。',
    category: 'business', level: 'beginner', type: 'article',
    tags: ['ドキュメント', 'README', 'API仕様', '技術文書'],
    url: 'https://www.google.com/search?q=エンジニア+ドキュメント作成',
    author: '各種技術ブログ', duration: '約60分', year: 2024,
  },
  {
    id: 'biz-004',
    title: 'SRE（サイトリライアビリティエンジニアリング）の実践',
    description: 'SLO・SLI・エラーバジェット・トイル削減・オンコール設計・ポストモーテム文化まで、Googleが生み出したSREの実践方法を学ぶ。',
    category: 'business', level: 'advanced', type: 'article',
    tags: ['SRE', 'SLO', 'SLI', 'エラーバジェット'],
    url: 'https://sre.google/sre-book/table-of-contents/',
    author: 'Google SRE Book', duration: '約4時間', year: 2024,
  },
  {
    id: 'biz-005',
    title: 'コードレビューの技術 ― 良いフィードバックの与え方',
    description: '指摘の仕方・受け方・レビューで何を見るか・自動化との棲み分けを解説。チームの生産性と品質を同時に高めるコードレビュー文化の作り方。',
    category: 'business', level: 'beginner', type: 'youtube',
    tags: ['コードレビュー', 'チーム開発', 'プルリクエスト', '品質'],
    url: 'https://www.youtube.com/watch?v=lSnbOtw4izI',
    youtubeId: 'lSnbOtw4izI',
    channel: 'Google for Developers', duration: '約60分', year: 2024,
  },

  // =================== 論文・研究 ===================
  {
    id: 'paper-001',
    title: 'Attention Is All You Need (Transformer 原著)',
    description: '現代の自然言語処理・生成AIの基盤となった歴史的論文。自己注意機構・マルチヘッドアテンション・位置エンコーディングの数学的定式化を理解する。',
    category: 'paper', level: 'advanced', type: 'paper',
    tags: ['Transformer', 'Attention', 'NLP', 'Google'],
    url: 'https://arxiv.org/abs/1706.03762',
    author: 'Vaswani et al., Google Brain (2017)', duration: '約4時間', year: 2017,
  },
  {
    id: 'paper-002',
    title: 'BERT: Pre-training of Deep Bidirectional Transformers',
    description: '双方向Transformerによる事前学習で多くのNLPタスクのSoTAを更新した論文。Masked LM・Next Sentence Predictionの仕組みを詳解。',
    category: 'paper', level: 'advanced', type: 'paper',
    tags: ['BERT', '事前学習', 'NLP', 'Google'],
    url: 'https://arxiv.org/abs/1810.04805',
    author: 'Devlin et al., Google AI Language (2018)', duration: '約3時間', year: 2018,
  },
  {
    id: 'paper-003',
    title: 'GPT-4 Technical Report',
    description: 'OpenAIによるGPT-4の技術報告書。評価手法・マルチモーダル能力・安全性研究・ハルシネーション対策まで、最先端LLMの開発実態を垣間見る。',
    category: 'paper', level: 'advanced', type: 'paper',
    tags: ['GPT-4', 'OpenAI', 'LLM', 'マルチモーダル'],
    url: 'https://arxiv.org/abs/2303.08774',
    author: 'OpenAI (2023)', duration: '約3時間', year: 2023,
  },
  {
    id: 'paper-004',
    title: 'ゼロトラストアーキテクチャ ― NIST SP 800-207',
    description: 'NIST（米国標準技術研究所）が定めたゼロトラストの定義・7原則・展開モデルを解説。境界型防御に替わる現代のネットワークセキュリティ設計の標準。',
    category: 'paper', level: 'advanced', type: 'paper',
    tags: ['ゼロトラスト', 'NIST', 'セキュリティアーキテクチャ'],
    url: 'https://csrc.nist.gov/publications/detail/sp/800-207/final',
    author: 'NIST (2020)', duration: '約3時間', year: 2020,
  },
  {
    id: 'paper-005',
    title: 'MapReduce: Simplified Data Processing on Large Clusters',
    description: 'GoogleのMapReduceフレームワーク原著論文。大規模分散処理の設計思想を理解することで、Hadoop・Spark・BigQueryなど現代技術の根底が見えてくる。',
    category: 'paper', level: 'advanced', type: 'paper',
    tags: ['MapReduce', '分散処理', 'Google', 'ビッグデータ'],
    url: 'https://research.google.com/archive/mapreduce.html',
    author: 'Dean & Ghemawat, Google (2004)', duration: '約2時間', year: 2004,
  },
  {
    id: 'paper-006',
    title: "Dynamo: Amazon's Highly Available Key-Value Store",
    description: 'AmazonのDynamo論文。結果整合性・ベクタークロック・コンシステントハッシュ・Gossipプロトコルなど、分散システム設計の必修トピックを実例で学ぶ。',
    category: 'paper', level: 'advanced', type: 'paper',
    tags: ['Dynamo', '分散システム', '結果整合性', 'Amazon'],
    url: 'https://www.allthingsdistributed.com/files/amazon-dynamo-sosp2007.pdf',
    author: 'DeCandia et al., Amazon (2007)', duration: '約3時間', year: 2007,
  },
];
